# Configure the build.
dist: xenial
jobs:
  fast_finish: true
  include:
    # PHP 7.3 Job. This only runs in the daily cron jobs.
    # Once infrastructure has been updated to 7.3+ this will be run on pull requests.
    - name: PHP 7.3
      language: php
      php: 7.3
      if: type = cron
      addons:
        apt:
          packages:
            - nginx
            - realpath
        hosts:
          - vanilla.test
      services:
        - mysql
      before_script:
        - phpenv config-rm xdebug.ini # Remove xdebug for better performance.
        - composer self-update
        - composer install --optimize-autoloader
        - tests/travis/setup.sh
      cache:
        directories:
          - $HOME/.composer/cache/files
      script:
        - tests/travis/main.sh
        - ls -lah ./conf
        - cat /tmp/error.log
        - cat /tmp/access.log
    # PHP 7.2 Job. This should always run.
    - name: PHP 7.2
      language: php
      php: 7.2
      addons:
        apt:
          packages:
            - nginx
            - realpath
        hosts:
          - vanilla.test
      services:
        - mysql
      before_script:
        - phpenv config-rm xdebug.ini # Remove xdebug for better performance.
        - composer self-update
        - composer install --optimize-autoloader
        - tests/travis/setup.sh
      cache:
        directories:
          - $HOME/.composer/cache/files
      script:
        - tests/travis/main.sh
        - ls -lah ./conf
        - cat /tmp/error.log
        - cat /tmp/access.log
    # PHP 7.1 Job. This only runs in the daily cron jobs.
    - name: PHP 7.1
      language: php
      php: 7.1
      if: type = cron
      addons:
        apt:
          packages:
            - nginx
            - realpath
        hosts:
          - vanilla.test
      services:
        - mysql
      before_script:
        - phpenv config-rm xdebug.ini # Remove xdebug for better performance.
        - composer self-update
        - composer install --optimize-autoloader
        - tests/travis/setup.sh
      cache:
        directories:
          - $HOME/.composer/cache/files
      script:
        - tests/travis/main.sh
        - ls -lah ./conf
        - cat /tmp/error.log
        - cat /tmp/access.log
    # PHP 7.0 Job. This only runs in the daily cron jobs.
    - name: PHP 7.0
      language: php
      php: 7.0
      if: type = cron
      addons:
        apt:
          packages:
            - nginx
            - realpath
        hosts:
          - vanilla.test
      services:
        - mysql
      before_script:
        - phpenv config-rm xdebug.ini # Remove xdebug for better performance.
        - composer self-update
        - composer install --optimize-autoloader
        - tests/travis/setup.sh
      cache:
        directories:
          - $HOME/.composer/cache/files
      script:
        - tests/travis/main.sh
        - ls -lah ./conf
        - cat /tmp/error.log
        - cat /tmp/access.log
    # Frontend JS Job
    - name: JS Build / Test
      language: node_js
      node_js: lts/*
      addons:
        apt:
          sources:
            - google-chrome
        chrome: stable
      before_script:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3 # Ensure a consistent yarn version
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn install --pure-lockfile
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/node_modules
          - $TRAVIS_BUILD_DIR/plugins/rich-editor/node_modules
        yarn: true
      script:
        - yarn build
        - yarn test
        - yarn check-types
        - ./tests/travis/audit.sh

# No additional system dependencies to install. Skip the install step.
install: true

env:
  - VANILLA_BUILD_DISABLE_AUTO_BUILD=true

# Send cron job notification to our Slack room.
notifications:
  slack:
    rooms:
      secure: cNkM+jJmkVUbXA1Fh9C9YF8Dp9N6SwRMPDYD9M5rz8KHjHg1qHhBFxrPab+e01r07W+FikUA4+dw5OstteW1iGIoQLtYevW4M+rKOQxZxjET/q/UpK2DAM3kNiWfPsKkSlLWssc8mwBbW4yaCesdADYma/NtQJq3YN983AEvHq4=
    on_success: always
    on_failure: always
    on_pull_requests: true

