# Configure the build.
jobs:
  fast_finish: true
  include:
    # PHP 7.2 Job. This should always run.
    - name: PHP 7.2
      language: php
      php: 7.2
      addons:
        apt:
          packages:
            - nginx
            - realpath
        hosts:
          - vanilla.test
      before_script:
        - phpenv config-rm xdebug.ini # Remove xdebug for better performance.
        - composer self-update
        - composer install --optimize-autoloader
        - tests/travis/setup.sh
      cache:
        directories:
          - $HOME/.composer/cache/files
      script:
        - tests/travis/main.sh
        - ls -lah ./conf
        - cat /tmp/error.log
        - cat /tmp/access.log
    # PHP 7.1 Job. This only runs in the daily cron jobs.
    - name: PHP 7.1
      language: php
      php: 7.1
      if: type = cron
      addons:
        apt:
          packages:
            - nginx
            - realpath
        hosts:
          - vanilla.test
      before_script:
        - phpenv config-rm xdebug.ini # Remove xdebug for better performance.
        - composer self-update
        - composer install --optimize-autoloader
        - tests/travis/setup.sh
      cache:
        directories:
          - $HOME/.composer/cache/files
      script:
        - tests/travis/main.sh
        - ls -lah ./conf
        - cat /tmp/error.log
        - cat /tmp/access.log
    # PHP 7.1 Job. This only runs in the daily cron jobs.
    - name: PHP 7.0
      language: php
      php: 7.0
      if: type = cron
      addons:
        apt:
          packages:
            - nginx
            - realpath
        hosts:
          - vanilla.test
      before_script:
        - phpenv config-rm xdebug.ini # Remove xdebug for better performance.
        - composer self-update
        - composer install --optimize-autoloader
        - tests/travis/setup.sh
      cache:
        directories:
          - $HOME/.composer/cache/files
      script:
        - tests/travis/main.sh
        - ls -lah ./conf
        - cat /tmp/error.log
        - cat /tmp/access.log
    # Frontend JS Job
    - name: JS Build / Test
      language: node_js
      node_js: lts/*
      addons:
        chrome: stable
      before_script:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4 # Ensure a consistent yarn version
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn install --pure-lockfile
        - cd plugins/rich-editor
        - yarn install
        - cd ../..
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/node_modules
          - $TRAVIS_BUILD_DIR/plugins/rich-editor/node_modules
        yarn: true
      script:
        - yarn run test
        - yarn run lint:ts

# No additional system dependencies to install. Skip the install step.
install: true

# Send status update notifications to a HipChat room.
notifications:
  hipchat:
    format: html
    on_success: change
    rooms:
      - secure: "SsKmSAZFynBz4ZKm5NPyuXvNjIMyxpNMXsgfXVImG8xjQHdXjEpZAiyckK8E2lXBBypv59Oex6wsS0RvyxpI/mwQ9dTQ9ayurQxwH3V5Q/+pRbtXJOkP+DSIsHhRb9D4xa5nPbh4N48+QZvUFiH2ety9/gev4mtMkLv3lC0vgpc="
    template:
      - '%{repository_slug} build <a href="%{build_url}">#%{build_number}</a> (%{branch} - <a href="%{compare_url}">%{commit}</a> by %{author}): %{message}'

# Run build in a Docker container. Reduces time between commit and start of build.
sudo: false
