sudo: false
before_install:
# Ensure a consistent yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH

# Install Vanilla and make symlinks
install:
  - ./travis/install.sh

# Cache Composer package files.
cache:
  directories:
    - $TRAVIS_BUILD_DIR/plugins/rich-editor/node_modules
    - $TRAVIS_BUILD_DIR/vanilla/tests/node_modules
    - $TRAVIS_BUILD_DIR/vanilla/applications/dashboard/node_modules
    - $TRAVIS_BUILD_DIR/vanilla/applications/dashboard/bower_components
  yarn: true

# The project's primary programming language. This will affect default dependency availability.
language: node_js

# Configure the build.
matrix:
  fast_finish: true

# The versions of PHP to test the project under.
node_js:
  - lts/*

# Steps of the build script.
script:
  - cd vanilla/tests
  - yarn test

env:
  - TEST_FILE_ROOTS = (plugins/rich-editor)

# Run build in a Docker container.  Reduces time between commit and start of build.
sudo: false
