# Add dependencies whitelisted by Travis and setup a loopback hostname for testing.
addons:
  chrome: stable
  apt:
    packages:
      - nginx
      - realpath
  hosts:
    - vanilla.test

# Steps to prepare for build script execution.
before_script:
  # PHP
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --optimize-autoloader
  - tests/travis/setup.sh
  # Node
  - cd tests
  - yarn install --pure-lockfile
  - cd ../
  - cd applications/dashboard
  - yarn install --pure-lockfile
  - cd ../..

# Cache Composer package files.
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.yarn-cache
    - $TRAVIS_BUILD_DIR/tests/node_modules
    - $TRAVIS_BUILD_DIR/applications/dashboard/node_modules
    - $TRAVIS_BUILD_DIR/applications/dashboard/bower_components
  yarn: true

# No additional system dependencies to install. Skip the install step.
install: true

# The project's primary programming language. This will affect default dependency availability.
language: php

# Configure the build.
matrix:
  fast_finish: true

# Send status update notifications to a HipChat room.
notifications:
  hipchat:
    format: html
    on_success: change
    rooms:
      - secure: "SsKmSAZFynBz4ZKm5NPyuXvNjIMyxpNMXsgfXVImG8xjQHdXjEpZAiyckK8E2lXBBypv59Oex6wsS0RvyxpI/mwQ9dTQ9ayurQxwH3V5Q/+pRbtXJOkP+DSIsHhRb9D4xa5nPbh4N48+QZvUFiH2ety9/gev4mtMkLv3lC0vgpc="
    template:
      - '%{repository_slug} build <a href="%{build_url}">#%{build_number}</a> (%{branch} - <a href="%{compare_url}">%{commit}</a> by %{author}): %{message}'

# The versions of PHP to test the project under.
php:
  - 7.0
  - 7.1
  - 7.2

# Steps of the build script.
script:
  - tests/travis/main.sh
  - cd tests
  - yarn run test
  - yarn run lint:ts
  - cd ../
  - ls -lah ./conf
  - cat /tmp/error.log
  - cat /tmp/access.log

# Run build in a Docker container. Reduces time between commit and start of build.
sudo: false
