version: 2
aliases:
    - &php72
        - image: circleci/php:7.2.9-node-browsers
    - &php73
        - image: circleci/php:7.3.5-node-browsers
    - &run_yarn
        run:
            name: Install Yarn Packages
            command: |
                cd ~/workspace/repo
                yarn install --pure-lockfile
                yarn install-all
    - &attach_workspace
        attach_workspace:
            at: ~/workspace
    - &run_composer
        run:
            name: Install Composer Packages
            command: |
                cd ~/workspace/repo
                VANILLA_BUILD_DISABLE_AUTO_BUILD=true composer install --optimize-autoloader
jobs:
    setup:
        docker: *php73
        steps:
            - run:
                name: Versions
                command: |
                    node --version
                    yarn --version
                    php --version
                    composer --version
            - checkout:
                path: ~/workspace/repo # Repository will be named repo.
            - run: |
                cd ~/workspace/repo
                rm -rf .git
            # We explcitly don't cache dependencies.
            # The cache validation & fetching seems to take longer than fetching from source.
            - *run_composer
            - *run_yarn
            - persist_to_workspace:
                root: ~/workspace
                paths:
                    - repo
    frontend_build:
        docker: *php73
        resource_class: xlarge
        steps:
            - *attach_workspace
            - run:
                name: Build Frontend
                command: |
                    cd ~/workspace/repo
                    yarn build
    frontend_test:
        docker: *php73
        resource_class: xlarge
        steps:
            - *attach_workspace
            - run:
                name: Build Frontend
                command: |
                    cd ~/workspace/repo
                    yarn test
    frontend_lint:
        docker: *php73
        working_directory: ~/
        steps:
            - *attach_workspace
            - run: |
                cd ~/workspace/repo
                yarn lint
                yarn prettier --check "**/src/scripts/**/*"
    frontend_typechecker:
        docker: *php73
        resource_class: large
        working_directory: ~/
        steps:
            - *attach_workspace
            - run: |
                cd ~/workspace/repo
                yarn check-types
workflows:
    version: 2
    commit:
        jobs:
            - setup
            - frontend_lint:
                requires:
                    - setup
            - frontend_typechecker:
                requires:
                    - setup
            - frontend_build:
                requires:
                    - setup
            - frontend_test:
                requires:
                    - setup