version: 2
aliases:
    - &php72
        - image: circleci/php:7.3.5-node
        - image: mysql:5.7.26
          environment:
                MYSQL_USER: root
                MYSQL_DATABASE: vanilla_test
                MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
                MYSQL_ROOT_PASSWORD: ''
    - &php73
        - image: circleci/php:7.2.19-node
        - image: mysql:5.7.26
          environment:
                MYSQL_USER: root
                MYSQL_DATABASE: vanilla_test
                MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
                MYSQL_ROOT_PASSWORD: ''
    - &node
        - image: circleci/node:lts-browsers
    - &run_yarn
        run:
            name: Install Yarn Packages
            command: |
                cd ~/workspace/frontend
                yarn install --pure-lockfile
                yarn install-all
    - &set_hosts
        run:
            name: Configuring Hosts
            command: |
                echo 127.0.0.1 vanilla.test | sudo tee -a /etc/hosts
                cat /etc/hosts
    - &attach_workspace
        attach_workspace:
            at: ~/workspace
    - &run_composer
        run:
            name: Install Composer Packages
            command: |
                cd ~/workspace/php
                VANILLA_BUILD_DISABLE_AUTO_BUILD=true composer install --optimize-autoloader
    - &run_php_lint
        run: |
            cd ~/workspace/php
            tests/travis/php-lint.sh ./applications
            tests/travis/php-lint.sh ./conf
            tests/travis/php-lint.sh ./library
            tests/travis/php-lint.sh ./plugins
            tests/travis/php-lint.sh ./themes
    - &await_mysql
        run:
            name: Waiting for MySQL to be ready
            command: |
                for i in `seq 1 30`;
                do
                nc -z 127.0.0.1 3306 && echo Success && exit 0
                echo -n .
                sleep 1
                done
                echo Failed waiting for MySQL && exit 1
    - phpunit_steps: &phpunit_steps
        - run:
            name: Versions
            command: |
                php --version
                composer --version
        - checkout:
            path: ~/workspace/php # Repository will be named repo.
        - run: |
            cd ~/workspace/php
            rm -rf .git
        # We explcitly don't cache dependencies.
        # The cache validation & fetching seems to take longer than fetching from source.
        - *run_composer
        - persist_to_workspace:
            root: ~/workspace
            paths:
                - php
        - *set_hosts
        - run:
            name: Test setup
            command: |
                cd ~/workspace/php
                cp ./tests/travis/templates/vanilla/conf/bootstrap.before.php ./conf/bootstrap.before.php
        - *await_mysql
        - run:
            name: Install openapi validator module
            command: |
                cd ~/workspace/php/plugins/swagger-ui/
                yarn install --pure-lockfile
        - run:
            name: Prepare Database Dependencies
            command: |
                sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
                sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
                sudo docker-php-ext-install pdo pdo_mysql gd
                sudo apt-get install mysql-client
        # - run:
        #     name: Create Test Table
        #     command: |
        #         mysql -h 127.0.0.1 -u root -e "create database vanilla_test;"
        - run:
            name: Library Tests
            command: |
                cd ~/workspace/php
                ./vendor/bin/phpunit -c phpunit.xml.dist --exclude-group=ignore --testsuite="Library"
        - run:
            name: Formatting Tests
            command: |
                cd ~/workspace/php
                ./vendor/bin/phpunit -c phpunit.xml.dist --exclude-group=ignore --testsuite="Formatting"
        - run:
            name: APIv2 Tests
            command: |
                cd ~/workspace/php
                ./vendor/bin/phpunit -c phpunit.xml.dist --exclude-group=ignore --testsuite="APIv2"
        - run:
            name: Models Tests
            command: |
                cd ~/workspace/php
                ./vendor/bin/phpunit -c phpunit.xml.dist --exclude-group=ignore --testsuite="Models"
jobs:
    frontend_setup:
        docker: *node
        steps:
            - run:
                name: Versions
                command: |
                    node --version
                    yarn --version
            - checkout:
                path: ~/workspace/frontend # Repository will be named repo.
            - run: |
                cd ~/workspace/frontend
                rm -rf .git
            # We explcitly don't cache dependencies.
            # The cache validation & fetching seems to take longer than fetching from source.
            - *run_yarn
            - persist_to_workspace:
                root: ~/workspace
                paths:
                    - frontend
    frontend_build:
        docker: *node
        resource_class: xlarge
        steps:
            - *attach_workspace
            - run:
                name: Build Frontend
                command: |
                    cd ~/workspace/frontend
                    yarn build
    frontend_test:
        docker: *node
        resource_class: xlarge
        steps:
            - *attach_workspace
            - run:
                name: Build Frontend
                command: |
                    cd ~/workspace/frontend
                    yarn test
    frontend_lint:
        docker: *node
        steps:
            - *attach_workspace
            - run: |
                cd ~/workspace/frontend
                yarn lint
                yarn prettier --check "**/src/scripts/**/*"
    frontend_typechecker:
        docker: *node
        resource_class: large
        steps:
            - *attach_workspace
            - run: |
                cd ~/workspace/frontend
                yarn check-types
    php_setup:
        docker: *php73
        steps:
            - run:
                name: Versions
                command: |
                    php --version
                    composer --version
            - checkout:
                path: ~/workspace/php # Repository will be named repo.
            - run: |
                cd ~/workspace/php
                rm -rf .git
            # We explcitly don't cache dependencies.
            # The cache validation & fetching seems to take longer than fetching from source.
            - *run_composer
            - persist_to_workspace:
                root: ~/workspace
                paths:
                    - php
    php_73_lint:
        docker: *php73
        steps:
            - *attach_workspace
            - *run_php_lint
    php_73_tests:
        docker: *php73
        resource_class: xlarge
        steps: *phpunit_steps
    php_72_lint:
        docker: *php72
        steps:
            - *attach_workspace
            - *run_php_lint
    php_72_tests:
        docker: *php72
        resource_class: xlarge
        steps: *phpunit_steps
workflows:
    version: 2
    commit:
        jobs:
            - frontend_setup
            - php_setup
            - frontend_lint:
                requires:
                    - frontend_setup
            - frontend_typechecker:
                requires:
                    - frontend_setup
            - frontend_build:
                requires:
                    - frontend_setup
            - frontend_test:
                requires:
                    - frontend_setup
            - php_73_lint:
                requires:
                    - php_setup
            - php_73_tests:
                requires:
                    - php_setup
            - php_72_lint:
                requires:
                    - php_setup
            - php_72_tests:
                requires:
                    - php_setup