version: 2
aliases:
    - &php72
        - image: circleci/php:7.2.9-node-browsers
    - &php73
        - image: circleci/php:7.3.5-node-browsers
    - &run_yarn
        run:
            name: Install Yarn Packages
            command: |
                cd ~/vanilla/repo
                yarn install --frozen-lockfile
    - &save_yarn_cache
        save_cache:
            paths:
                - ~/.cache/yarn
            key: yarn-packages-v1-{{ .Branch }}-{{ checksum "~/vanilla/repo/yarn.lock" }}
    - &restore_yarn_cache
        restore_cache:
            name: Restore node_modules cache
            keys:
                - yarn-packages-v1-{{ .Branch }}-{{ checksum "~/vanilla/repo/yarn.lock" }}
                - yarn-packages-v1-{{ .Branch }}-
                - yarn-packages-v1-
    - &attach_workspace
        attach_workspace:
            at: ~/vanilla/repo
    - &save_composer_cache
        save_cache:
            key: composer-v1-{{ checksum "~/vanilla/repo/composer.lock" }}
            paths:
                - vendor
    - &restore_composer_cache
        restore_cache:
            keys:
                - composer-v1-{{ checksum "~/vanilla/repo/composer.lock" }}
                - composer-v1-
    - &run_composer
        run:
            name: Install Composer Packages
            command: |
                cd ~/vanilla/repo
                VANILLA_BUILD_DISABLE_AUTO_BUILD=true composer install --optimize-autoloader
jobs:
    setup:
        docker: *php73
        resource_class: xlarge
        steps:
            - run:
                name: Versions
                command: |
                    node --version
                    yarn --version
                    php --version
                    composer --version
            - checkout:
                path: ~/vanilla/repo
            - run: |
                cd ~/vanilla/repo
                rm -rf .git
            - *restore_composer_cache
            - *run_composer
            - *save_composer_cache
            - *restore_yarn_cache
            - *run_yarn
            - run:
                name: Build Frontend
                command: |
                    cd ~/vanilla/repo
                    yarn build
            - *save_yarn_cache
            - persist_to_workspace:
                root: ~/vanilla
                paths:
                    - repo
    frontend_lint:
        docker: *php73
        working_directory: ~/
        steps:
            - *attach_workspace
            - run: |
                cd ~/vanilla/repo
                yarn lint
                yarn prettier --check "**/src/scripts/**/*"
    frontend_typechecker:
        docker: *php73
        resource_class: large
        working_directory: ~/
        steps:
            - *attach_workspace
            - run: |
                cd ~/vanilla/repo
                yarn check-types
workflows:
    version: 2
    commit:
        jobs:
            - setup
            - frontend_lint:
                requires:
                    - setup
            - frontend_typechecker:
                requires:
                    - setup
