version: 2
aliases:
    - &php72
        - image: circleci/php:7.2.9-node-browsers
    - &php73
        - image: circleci/php:7.3.5-node-browsers
    - &run_yarn
        run:
            name: Install Yarn Packages
            command: yarn install --frozen-lockfile
    - &save_yarn_cache
        save_cache:
            paths:
                - ~/.cache/yarn
            key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
    - &restore_yarn_cache
        restore_cache:
            name: Restore node_modules cache
            keys:
                - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
                - yarn-packages-v1-{{ .Branch }}-
                - yarn-packages-v1-
    - &attach_workspace
        attach_workspace:
            at: ~/repo
        run: cd ~/repo
    - &save_composer_cache
        save_cache:
            key: composer-v1-{{ checksum "composer.lock" }}
            paths:
                - vendor
    - &restore_composer_cache
        restore_cache:
            keys:
                - composer-v1-{{ checksum "composer.lock" }}
                - composer-v1-
    - &run_composer
        run:
            name: Install Composer Packages
            command: VANILLA_BUILD_DISABLE_AUTO_BUILD=true composer install --optimize-autoloader
jobs:
    setup:
        docker: *php73
        working_directory: ~/
        resource_class: xlarge
        steps:
            - checkout:
                path: ~/repo
            - run: cd ~/repo
            - run: rm -rf .git
            - run:
                name: Nodejs Version
                command: node --version
            - *restore_composer_cache
            - *run_composer
            - *save_composer_cache
            - *restore_yarn_cache
            - *run_yarn
            - run:
                name: Build Frontend
                command: yarn build
            - *save_yarn_cache
            - persist_to_workspace:
                root: ~/
                paths:
                    - repo
    frontend_lint:
        docker: *php73
        steps:
            - *attach_workspace
            - run: yarn lint
            - run: yarn prettier --check "**/src/scripts/**/*"
    frontend_typechecker:
        docker: *php73
        steps:
            - *attach_workspace
            - *restore_yarn_cache
            - *run_yarn
            - run: yarn check-types
workflows:
    version: 2
    commit:
        jobs:
            - setup
            - frontend_lint:
                requires:
                    - setup
            - frontend_typechecker:
                requires:
                    - setup
